#!/usr/bin/env python3
"""Convert the CALM JSON-Schema specification into a LinkML schema.

The Common Architecture Language Model (CALM) is distributed as a set of
JSON-Schema files under ``calm/release/<version>/meta/`` in this monorepo.
This script reads those JSON-Schema files and emits a single LinkML YAML
schema at ``linkml/src/calm/schema/calm.yaml`` augmented with enrichments
that JSON-Schema cannot express (ontology mappings, ``slot_uri`` wiring,
subset tags, folded descriptions, identifiers, ...).

Usage::

    cd linkml
    uv run python scripts/calm_to_linkml.py             # writes src/calm/schema/calm.yaml
    uv run python scripts/calm_to_linkml.py --check     # exits non-zero if drift
    uv run python scripts/calm_to_linkml.py --stdout    # write to stdout

Conversion rules at a glance:

* Each JSON-Schema ``defs/<name>`` becomes a LinkML ``class`` (PascalCase).
* Each scalar JSON property becomes a LinkML ``slot`` (snake_case),
  with hyphens in the source name preserved in ``aliases``.
* JSON ``enum`` arrays become LinkML ``enums`` (PascalCase).
* ``$ref`` to a sibling/foreign def is resolved into a ``range:`` reference.
* ``oneOf`` / ``anyOf`` at the property level become ``any_of`` on the slot,
  with an explicit list of alternative ranges (see SKILL note on
  ``gen-json-schema`` union expansion).
* ``required`` arrays mark slots as ``required: true``; ``pattern`` becomes
  a ``pattern:`` constraint; ``minItems: 1`` plus ``type: array`` becomes a
  ``required, multivalued`` combination on the host slot.
* Hand-curated overlays in ``ENRICHMENTS`` add ``description``,
  ``slot_uri``, ``class_uri``, ``*_mappings``, ``in_subset``, etc.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import textwrap
from collections import OrderedDict
from pathlib import Path
from typing import Any, Iterable

import yaml

# ---------------------------------------------------------------------------
# Paths / constants
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parents[2]
LINKML_ROOT = REPO_ROOT / "linkml"
CALM_VERSION = "1.2"
SOURCE_META_DIR = REPO_ROOT / "calm" / "release" / CALM_VERSION / "meta"
SCHEMA_PATH = LINKML_ROOT / "src" / "calm" / "schema" / "calm.yaml"

SCHEMA_ID = "https://w3id.org/lmodel/calm"
SCHEMA_NAME = "calm"
DEFAULT_PREFIX = "calm"

# Per-file JSON-Schema sources to read (order is preserved when emitting).
SCHEMA_FILES: tuple[str, ...] = (
    "core.json",
    "control.json",
    "control-requirement.json",
    "decorators.json",
    "evidence.json",
    "flow.json",
    "interface.json",
    "timeline.json",
    "units.json",
)

# JSON-Schema umbrella files (delegate via ``allOf``); they hold no defs.
UMBRELLA_FILES: tuple[str, ...] = ("calm.json", "calm-timeline.json")

GENERATED_HEADER = (
    "# AUTOGENERATED -- DO NOT EDIT BY HAND.\n"
    "# Regenerate with: ``uv run python scripts/calm_to_linkml.py``\n"
    "# Source of truth: linkml/scripts/calm_to_linkml.py + calm/release/"
    + CALM_VERSION
    + "/meta/*.json\n"
)

# ---------------------------------------------------------------------------
# YAML emission helpers
# ---------------------------------------------------------------------------

_FOLD_WIDTH = 78
_LITERAL_WRAP = 76


def _wrap_paragraphs(text: str, width: int) -> str:
    """Wrap each paragraph of ``text`` to ``width`` columns."""
    paragraphs = re.split(r"\n\s*\n", text)
    out: list[str] = []
    for para in paragraphs:
        collapsed = " ".join(para.split())
        if not collapsed:
            continue
        out.append(
            textwrap.fill(
                collapsed,
                width=width,
                break_long_words=False,
                break_on_hyphens=False,
            )
        )
    return "\n\n".join(out)


class _OrderedDumper(yaml.SafeDumper):
    """Emit dicts in insertion order with indented list items."""

    def increase_indent(self, flow: bool = False, indentless: bool = False) -> Any:  # type: ignore[override]
        return super().increase_indent(flow=flow, indentless=False)


def _ordered_dict_representer(dumper: yaml.SafeDumper, data: dict) -> yaml.MappingNode:
    return dumper.represent_mapping(
        yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG,
        list(data.items()),
    )


def _str_representer(dumper: yaml.SafeDumper, data: str) -> yaml.ScalarNode:
    if "\n" in data:
        wrapped = _wrap_paragraphs(data, _LITERAL_WRAP)
        return dumper.represent_scalar("tag:yaml.org,2002:str", wrapped, style="|")
    if len(data) > _FOLD_WIDTH and " " in data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style=">")
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


_OrderedDumper.add_representer(dict, _ordered_dict_representer)
_OrderedDumper.add_representer(OrderedDict, _ordered_dict_representer)
_OrderedDumper.add_representer(str, _str_representer)


def _dump_yaml(data: Any) -> str:
    return yaml.dump(
        data,
        Dumper=_OrderedDumper,
        default_flow_style=False,
        sort_keys=False,
        width=_FOLD_WIDTH,
        allow_unicode=True,
        indent=2,
    )


_ENTRY_RE = re.compile(r"^  [A-Za-z_][\w]*:")


def _add_entry_blanks(section_text: str) -> str:
    """Insert a single blank line before each second-level entry in a block."""
    lines = section_text.split("\n")
    out: list[str] = []
    seen_entry = False
    for line in lines:
        if _ENTRY_RE.match(line):
            if seen_entry:
                out.append("")
            seen_entry = True
        out.append(line)
    return "\n".join(out)


def _emit_section(key: str, value: Any, *, blank_between_entries: bool = False) -> str:
    if value is None:
        return ""
    if isinstance(value, (dict, list)) and len(value) == 0:
        return ""
    text = _dump_yaml({key: value}).rstrip() + "\n"
    if blank_between_entries:
        text = _add_entry_blanks(text)
    return text


def _emit_scalar(key: str, value: Any) -> str:
    if value is None:
        return ""
    return _dump_yaml({key: value}).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Naming helpers
# ---------------------------------------------------------------------------


def to_pascal_case(name: str) -> str:
    """``some-thing`` / ``some_thing`` -> ``SomeThing``."""
    parts = re.split(r"[-_\s]+", name)
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


def to_snake_case(name: str) -> str:
    """``some-thing`` / ``SomeThing`` -> ``some_thing``."""
    s = re.sub(r"[-\s]+", "_", name)
    s = re.sub(r"(?<!^)(?=[A-Z])", "_", s).lower()
    return s.replace("__", "_")


def to_enum_value(name: str) -> str:
    """``source-to-destination`` -> ``source_to_destination``; preserve case."""
    return re.sub(r"[-\s]+", "_", name)


# ---------------------------------------------------------------------------
# Loader
# ---------------------------------------------------------------------------


def load_json_schema(filename: str, source_dir: Path = SOURCE_META_DIR) -> dict:
    """Load and parse one CALM JSON-Schema meta file."""
    path = source_dir / filename
    return json.loads(path.read_text(encoding="utf-8"))


def load_all_schemas(source_dir: Path = SOURCE_META_DIR) -> "OrderedDict[str, dict]":
    """Load every CALM meta JSON-Schema file in declared order."""
    out: "OrderedDict[str, dict]" = OrderedDict()
    for fname in SCHEMA_FILES:
        out[fname] = load_json_schema(fname, source_dir)
    return out


# ---------------------------------------------------------------------------
# Definition / class name registry
# ---------------------------------------------------------------------------

# Maps (filename, def_name | None) -> LinkML class name.  ``None`` denotes the
# root object of a schema file.
DEFINITION_CLASSES: dict[tuple[str, str | None], str] = {
    # core.json
    ("core.json", None): "Architecture",
    ("core.json", "node"): "Node",
    ("core.json", "relationship"): "Relationship",
    ("core.json", "interacts-type"): "InteractsRelationship",
    ("core.json", "connects-type"): "ConnectsRelationship",
    ("core.json", "deployed-in-type"): "DeployedInRelationship",
    ("core.json", "composed-of-type"): "ComposedOfRelationship",
    ("core.json", "decision"): "Decision",
    # control.json
    ("control.json", "control-detail"): "ControlDetail",
    ("control.json", "controls"): "Control",
    # control-requirement.json
    ("control-requirement.json", None): "ControlRequirement",
    # decorators.json
    ("decorators.json", "decorator"): "Decorator",
    # evidence.json
    ("evidence.json", None): "EvidenceDocument",
    # flow.json
    ("flow.json", "flow"): "Flow",
    ("flow.json", "transition"): "Transition",
    # interface.json
    ("interface.json", "interface-definition"): "InterfaceDefinition",
    ("interface.json", "interface-type"): "InterfaceType",
    ("interface.json", "node-interface"): "NodeInterface",
    # timeline.json
    ("timeline.json", None): "Timeline",
    ("timeline.json", "node-moment"): "NodeMoment",
    # units.json
    ("units.json", "time-unit"): "TimeUnit",
    ("units.json", "rate-unit"): "RateUnit",
}

# Maps a JSON-Schema ``$ref`` to a LinkML range (class or type name).
# Keys are normalized as ``<filename>#/defs/<name>`` or ``#/defs/<name>``.
REF_TARGETS: dict[str, str] = {
    "#/defs/node": "Node",
    "#/defs/relationship": "Relationship",
    "#/defs/interacts-type": "InteractsRelationship",
    "#/defs/connects-type": "ConnectsRelationship",
    "#/defs/deployed-in-type": "DeployedInRelationship",
    "#/defs/composed-of-type": "ComposedOfRelationship",
    "#/defs/option-type": "OptionList",
    "#/defs/decision": "Decision",
    "#/defs/metadata": "Metadata",
    "#/defs/protocol": "Protocol",
    "#/defs/node-type-definition": "NodeType",
    "control.json#/defs/controls": "Control",
    "control.json#/defs/control-detail": "ControlDetail",
    "core.json#/defs/metadata": "Metadata",
    "core.json#/defs/node": "Node",
    "flow.json#/defs/flow": "Flow",
    "flow.json#/defs/transition": "Transition",
    "interface.json#/defs/interface-definition": "InterfaceDefinition",
    "interface.json#/defs/interface-type": "InterfaceType",
    "interface.json#/defs/node-interface": "NodeInterface",
}


def resolve_ref(ref: str) -> str:
    """Translate a JSON-Schema ``$ref`` into a LinkML ``range`` value."""
    key = ref.strip()
    if key in REF_TARGETS:
        return REF_TARGETS[key]
    # Tolerate either local (``#/defs/x``) or scoped (``foo.json#/defs/x``).
    local = key.split("#", 1)[-1]
    local_key = "#" + local if not local.startswith("#") else local
    if local_key in REF_TARGETS:
        return REF_TARGETS[local_key]
    # Last resort: derive PascalCase from the final ``defs/<name>`` segment.
    tail = local.rsplit("/", 1)[-1]
    return to_pascal_case(tail) if tail else "string"


# ---------------------------------------------------------------------------
# JSON-Schema -> LinkML type mapping
# ---------------------------------------------------------------------------

JSON_TO_LINKML_SCALAR: dict[str, str] = {
    "string": "string",
    "integer": "integer",
    "number": "float",
    "boolean": "boolean",
    "object": "Metadata",
}


def json_scalar_to_linkml(json_type: str) -> str:
    """Map a primitive JSON-Schema ``type`` keyword to a LinkML range."""
    return JSON_TO_LINKML_SCALAR.get(json_type, "string")


# ---------------------------------------------------------------------------
# Property -> slot conversion
# ---------------------------------------------------------------------------


def slot_name_for(prop_name: str) -> str:
    """Convert a JSON property name (hyphenated) into a LinkML slot name."""
    return prop_name.replace("-", "_")


def convert_property(
    prop_name: str,
    prop: dict,
    *,
    required: bool,
) -> dict:
    """Convert one JSON-Schema property body into a LinkML slot body."""
    body: dict[str, Any] = {}

    desc = prop.get("description")
    if desc:
        body["description"] = desc

    # array ->  multivalued + element range
    if prop.get("type") == "array":
        items = prop.get("items") or {}
        if "$ref" in items:
            body["range"] = resolve_ref(items["$ref"])
        elif "anyOf" in items:
            body["any_of"] = _convert_choice_list(items["anyOf"])
            body["range"] = body["any_of"][0]["range"]
        elif items.get("type") == "object":
            body["range"] = "Metadata"
        else:
            body["range"] = json_scalar_to_linkml(items.get("type", "string"))
        body["multivalued"] = True
        if prop.get("minItems") and prop["minItems"] >= 1 and required:
            body["required"] = True
        elif required:
            body["required"] = True
        return body

    # $ref ->  reference to another class/type
    if "$ref" in prop:
        body["range"] = resolve_ref(prop["$ref"])
        if required:
            body["required"] = True
        return body

    # anyOf at property level ->  any_of
    if "anyOf" in prop:
        body["any_of"] = _convert_choice_list(prop["anyOf"])
        # The first alt becomes the nominal range so generators downstream
        # always have a concrete fallback type to emit.
        body["range"] = body["any_of"][0]["range"]
        if required:
            body["required"] = True
        return body

    # enum inline ->  emit as string with constrained values via pattern
    if "enum" in prop:
        body["range"] = "string"
        if required:
            body["required"] = True
        return body

    # const ->  equals_string
    if "const" in prop:
        body["range"] = "string"
        body["equals_string"] = prop["const"]
        if required:
            body["required"] = True
        return body

    json_type = prop.get("type", "string")
    if json_type == "object":
        body["range"] = "Metadata"
    else:
        body["range"] = json_scalar_to_linkml(json_type)

    if "pattern" in prop:
        body["pattern"] = prop["pattern"]
    if "format" in prop:
        body["annotations"] = {"json_format": prop["format"]}
    if "minimum" in prop:
        body["minimum_value"] = prop["minimum"]
    if "maximum" in prop:
        body["maximum_value"] = prop["maximum"]
    if "default" in prop:
        default = prop["default"]
        if isinstance(default, str):
            body["ifabsent"] = f"string({default})"
        elif isinstance(default, bool):
            body["ifabsent"] = f"boolean({str(default).lower()})"
        elif isinstance(default, int):
            body["ifabsent"] = f"int({default})"

    if required:
        body["required"] = True
    return body


def _convert_choice_list(alternatives: Iterable[dict]) -> list[dict]:
    """Turn a list of JSON-Schema alternatives into LinkML ``any_of`` form."""
    out: list[dict] = []
    for alt in alternatives:
        if "$ref" in alt:
            out.append({"range": resolve_ref(alt["$ref"])})
        elif alt.get("type") == "array":
            out.append({"range": "Metadata", "multivalued": True})
        elif alt.get("type") == "object":
            out.append({"range": "Metadata"})
        else:
            out.append({"range": json_scalar_to_linkml(alt.get("type", "string"))})
    return out


# ---------------------------------------------------------------------------
# Enrichments
# ---------------------------------------------------------------------------

# Slot-level enrichments applied after JSON-Schema conversion. Merged
# shallowly into the slot body, overwriting JSON-derived values when the
# overlay is more specific.
SLOT_ENRICHMENTS: dict[str, dict[str, Any]] = {
    "unique_id": {
        "identifier": True,
        "required": True,
        "slot_uri": "schema:identifier",
        "aliases": ["unique-id"],
        "description": "Stable opaque identifier used to cross-link CALM elements.",
    },
    "name": {
        "slot_uri": "rdfs:label",
        "description": "Short human-readable name.",
    },
    "description": {
        "slot_uri": "dct:description",
        "description": "Free-form description of the element.",
        "required": None,  # not globally required; set per-class via slot_usage
    },
    "url": {
        "slot_uri": "schema:url",
    },
    "requirement_url": {
        "aliases": ["requirement-url"],
        "slot_uri": "schema:url",
        "required": None,  # not globally required; only ControlDetail requires it
    },
    "config_url": {
        "aliases": ["config-url"],
        "slot_uri": "schema:url",
    },
    "definition_url": {
        "aliases": ["definition-url"],
        "slot_uri": "schema:url",
    },
    "control_config_url": {
        "aliases": ["control-config-url"],
        "slot_uri": "schema:url",
    },
    "valid_from": {
        "aliases": ["valid-from"],
        "range": "date",
        "slot_uri": "prov:startedAtTime",
    },
    "sequence_number": {
        "aliases": ["sequence-number"],
        "range": "integer",
        "minimum_value": 1,
    },
    "node_type": {
        "aliases": ["node-type"],
        "range": "NodeType",
        "description": "Category of the node (system, service, actor, etc.).",
        "any_of": [{"range": "NodeType"}, {"range": "string"}],
    },
    "relationship_type": {
        "aliases": ["relationship-type"],
        "range": "RelationshipType",
    },
    "evidence_paths": {
        "aliases": ["evidence-paths"],
        "multivalued": True,
        "range": "string",
        "description": "Paths (filesystem or URL) pointing at supporting evidence.",
    },
    "relationship_unique_id": {
        "aliases": ["relationship-unique-id"],
        "range": "string",
    },
    "applies_to": {
        "aliases": ["applies-to"],
        "multivalued": True,
        "range": "string",
    },
    "current_moment": {
        "aliases": ["current-moment"],
        "range": "string",
    },
    "control_id": {
        "aliases": ["control-id"],
        "range": "string",
        "identifier": True,
        "required": True,
    },
    # interfaces: strip the any_of generated from the JSON-Schema anyOf
    # (InterfaceDefinition | InterfaceType) so that inlined_as_list in
    # class slot_usage produces a clean $ref without the anyOf[string]
    # sibling that LinkML's JSON-Schema generator otherwise emits.
    "interfaces": {
        "description": "Interface definitions exposed by nodes.",
        "range": "InterfaceDefinition",
        "any_of": None,  # delete the generated any_of
    },
    "direction": {
        "range": "TransitionDirection",
        "description": "Direction of flow on the transition.",
    },
    "unit": {
        "range": "TimeUnitName",
        "description": "The unit of time (e.g., seconds, minutes, hours).",
    },
    "per": {
        "range": "RatePerUnit",
        "description": "The time unit defining the rate interval.",
    },
}

# Class-level enrichments applied after JSON-Schema conversion.
CLASS_ENRICHMENTS: dict[str, dict[str, Any]] = {
    "Architecture": {
        "tree_root": True,
        "description": "Top-level CALM architecture document.",
        "class_uri": "calm:Architecture",
        "in_subset": ["core"],
        "close_mappings": ["schema:SoftwareApplication"],
        # Architectures always embed full Node/Relationship/Flow objects inline.
        # slot_usage overrides are needed because the schema-level `nodes`,
        # `relationships`, and `flows` slots have no inlining by default
        # (since Node and Relationship carry identifier slots).
        "slot_usage": {
            "nodes": {"inlined": True, "inlined_as_list": True},
            "relationships": {"inlined": True, "inlined_as_list": True},
            "flows": {"inlined": True, "inlined_as_list": True},
        },
    },
    "Node": {
        "description": "A logical or physical element of an architecture (system, service, actor, ...).",
        "class_uri": "calm:Node",
        "in_subset": ["core"],
        "close_mappings": ["schema:Thing"],
        # Interfaces are always embedded as full objects inside a Node.
        "slot_usage": {
            "interfaces": {"inlined": True, "inlined_as_list": True},
            "description": {"required": True},
        },
    },
    "Relationship": {
        "description": "A typed link between architecture elements.",
        "class_uri": "calm:Relationship",
        "in_subset": ["core"],
        "related_mappings": ["prov:wasInfluencedBy"],
    },
    "Control": {
        "description": "A named control attached to an architecture element.",
        "class_uri": "calm:Control",
        "in_subset": ["control_framework"],
        "related_mappings": ["schema:Action"],
    },
    "ControlDetail": {
        "description": "A single control requirement and its inline / referenced configuration.",
        "class_uri": "calm:ControlDetail",
        "in_subset": ["control_framework"],
        "slot_usage": {
            "requirement_url": {"required": True},
        },
    },
    "ControlRequirement": {
        "description": "Domain-defined control requirement that controls can reference.",
        "class_uri": "calm:ControlRequirement",
        "in_subset": ["control_framework"],
        "slot_usage": {
            "description": {"required": True},
        },
    },
    "Decorator": {
        "description": "Cross-cutting annotation attached to nodes, relationships, or flows.",
        "class_uri": "calm:Decorator",
        "in_subset": ["decorators"],
    },
    "EvidenceDocument": {
        "description": "Top-level CALM evidence document linking control configurations to evidence artefacts.",
        "class_uri": "calm:EvidenceDocument",
        "in_subset": ["control_framework"],
    },
    "Flow": {
        "description": "Business flow mapped onto architecture relationships.",
        "class_uri": "calm:Flow",
        "in_subset": ["flow_modeling"],
        "slot_usage": {
            "description": {"required": True},
        },
    },
    "Transition": {
        "description": "A single step in a flow, anchored on a relationship.",
        "class_uri": "calm:Transition",
        "in_subset": ["flow_modeling"],
        "slot_usage": {
            "description": {"required": True},
        },
    },
    "InterfaceDefinition": {
        "description": "Modular interface definition referencing an external schema.",
        "class_uri": "calm:InterfaceDefinition",
        "in_subset": ["interface_defs"],
        "slot_usage": {
            "config": {"required": True},
        },
    },
    "InterfaceType": {
        "description": "Inline (free-form) interface definition keyed by unique-id.",
        "class_uri": "calm:InterfaceType",
        "in_subset": ["interface_defs"],
    },
    "NodeInterface": {
        "description": "Reference to one or more interfaces exposed by a node.",
        "class_uri": "calm:NodeInterface",
        "in_subset": ["interface_defs"],
        # Interfaces inside a NodeInterface are always embedded inline.
        "slot_usage": {
            "interfaces": {"inlined": True, "inlined_as_list": True},
        },
    },
    "Timeline": {
        "tree_root": True,
        "description": "CALM timeline document capturing architecture moments over time.",
        "class_uri": "calm:Timeline",
        "in_subset": ["timeline"],
    },
    "NodeMoment": {
        "is_a": "Node",
        "description": "An architecture moment - a point-in-time snapshot of the architecture.",
        "class_uri": "calm:NodeMoment",
        "in_subset": ["timeline"],
        "slot_usage": {
            "details": {"required": True},
        },
    },
    "TimeUnit": {
        "description": "A quantity of time expressed as a numeric value and a unit.",
        "class_uri": "calm:TimeUnit",
        "in_subset": ["units"],
        "exact_mappings": ["schema:Duration"],
    },
    "RateUnit": {
        "description": "A rate (count per time unit), e.g. operations per second.",
        "class_uri": "calm:RateUnit",
        "in_subset": ["units"],
    },
    "Decision": {
        "description": "A candidate decision within an ``options`` relationship.",
        "class_uri": "calm:Decision",
        "in_subset": ["core"],
        # A Decision is an alternative mini-architecture; nodes and relationships
        # are embedded inline just as they are in a top-level Architecture.
        "slot_usage": {
            "nodes": {"inlined": True, "inlined_as_list": True, "required": True},
            "relationships": {"inlined": True, "inlined_as_list": True, "required": True},
            "description": {"required": True},
        },
    },
    "InteractsRelationship": {
        "description": "An ``interacts`` relationship between an actor and one or more nodes.",
        "class_uri": "calm:InteractsRelationship",
        "in_subset": ["core"],
        "slot_usage": {
            "nodes": {"required": True},
        },
    },
    "ConnectsRelationship": {
        "description": "A ``connects`` relationship between two node interfaces.",
        "class_uri": "calm:ConnectsRelationship",
        "in_subset": ["core"],
    },
    "DeployedInRelationship": {
        "description": "A ``deployed-in`` containment relationship.",
        "class_uri": "calm:DeployedInRelationship",
        "in_subset": ["core"],
        "slot_usage": {
            "nodes": {"required": True},
        },
    },
    "ComposedOfRelationship": {
        "description": "A ``composed-of`` containment relationship.",
        "class_uri": "calm:ComposedOfRelationship",
        "in_subset": ["core"],
        "slot_usage": {
            "nodes": {"required": True},
        },
    },
}


# ---------------------------------------------------------------------------
# Schema sections
# ---------------------------------------------------------------------------


def header_block() -> str:
    """Schema-level metadata fields."""
    data: dict[str, Any] = {
        "id": SCHEMA_ID,
        "name": SCHEMA_NAME,
        "title": "Common Architecture Language Model (CALM)",
        "description": (
            "LinkML representation of the FINOS Common Architecture Language "
            "Model (CALM) " + CALM_VERSION + " specification. CALM is a "
            "declarative, JSON-based modeling language for describing complex "
            "software architectures (nodes, relationships, controls, flows, "
            "decorators, timelines, evidence, and units). This LinkML schema "
            "is generated from the CALM JSON-Schema meta files."
        ),
        "license": "Apache-2.0",
        "see_also": [
            "https://calm.finos.org/",
            "https://github.com/finos/architecture-as-code",
        ],
        "source": (
            "https://calm.finos.org/release/" + CALM_VERSION + "/meta/calm.json"
        ),
        "version": CALM_VERSION,
    }
    return _dump_yaml(data).rstrip() + "\n"


def prefixes_block() -> dict:
    return {
        "calm": "https://w3id.org/lmodel/calm/",
        "linkml": "https://w3id.org/linkml/",
        "schema": "http://schema.org/",
        "dct": "http://purl.org/dc/terms/",
        "skos": "http://www.w3.org/2004/02/skos/core#",
        "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "xsd": "http://www.w3.org/2001/XMLSchema#",
        "owl": "http://www.w3.org/2002/07/owl#",
        "prov": "http://www.w3.org/ns/prov#",
        "finos_calm": "https://calm.finos.org/release/" + CALM_VERSION + "/meta/",
        "ai_governance_framework": "https://w3id.org/lmodel/ai-governance-framework/",
    }


def imports_block() -> list[str]:
    return ["linkml:types"]


def subsets_block() -> dict:
    return {
        "core": {"description": "Core architecture vocabulary (nodes, relationships, decisions)."},
        "control_framework": {"description": "Control framework: controls, requirements, evidence."},
        "flow_modeling": {"description": "Business flow modeling: flows and transitions."},
        "interface_defs": {"description": "Interface definitions exposed by nodes."},
        "decorators": {"description": "Cross-cutting decorators that annotate elements."},
        "timeline": {"description": "Time-based architecture snapshots (moments)."},
        "units": {"description": "Quantity and rate unit primitives."},
    }


def types_block() -> dict:
    return {
        "CronExpression": {
            "uri": "xsd:string",
            "base": "str",
            "description": "A Unix-style cron expression (minute, hour, day, month, weekday).",
            "pattern": r"^([0-5]?\d)\s([01]?\d|2[0-3])\s(3[01]|[12]\d|0?[1-9])\s(1[0-2]|0?[1-9])\s([0-6])$",
        },
        "Metadata": {
            "uri": "xsd:string",
            "base": "str",
            "description": (
                "Opaque key/value metadata payload. JSON-Schema allows either an "
                "object or an array of objects; in LinkML this is modeled as a "
                "permissive string type that downstream consumers parse as JSON."
            ),
        },
    }


# ---------------------------------------------------------------------------
# Enums (extracted from JSON schemas + enriched)
# ---------------------------------------------------------------------------


def enums_block(schemas: "OrderedDict[str, dict]") -> dict:
    core = schemas["core.json"]
    units = schemas["units.json"]
    flow = schemas["flow.json"]

    protocol_values = core["defs"]["protocol"]["enum"]
    node_type_enum = core["defs"]["node-type-definition"]["anyOf"][0]["enum"]
    time_unit_values = units["defs"]["time-unit"]["properties"]["unit"]["enum"]
    rate_per_values = units["defs"]["rate-unit"]["properties"]["per"]["enum"]
    direction_values = flow["defs"]["transition"]["properties"]["direction"]["enum"]

    out: "OrderedDict[str, dict]" = OrderedDict()
    out["Protocol"] = {
        "description": "Wire-level protocol used by a relationship.",
        "permissible_values": {
            v: {"description": f"The {v} protocol.", "meaning": f"calm:protocol/{v}"}
            for v in protocol_values
        },
    }
    out["NodeType"] = {
        "description": (
            "Category of architecture node. The CALM JSON-Schema allows arbitrary "
            "strings; this enum lists the canonical values plus an escape hatch via "
            "``any_of`` on the slot."
        ),
        "permissible_values": {
            to_enum_value(v): {
                "description": f"A {v} node.",
                "meaning": f"calm:node-type/{v}",
            }
            for v in node_type_enum
        },
    }
    out["TimeUnitName"] = {
        "description": "Named unit of time used by ``TimeUnit``.",
        "permissible_values": {
            v: {"description": f"Time unit: {v}."} for v in time_unit_values
        },
    }
    out["RatePerUnit"] = {
        "description": "Time interval denominator used by ``RateUnit``.",
        "permissible_values": {
            v: {"description": f"Rate denominator: per {v}."} for v in rate_per_values
        },
    }
    out["TransitionDirection"] = {
        "description": "Direction of flow on a transition.",
        "permissible_values": {
            to_enum_value(v): {"description": f"Flow direction: {v}."}
            for v in direction_values
        },
    }
    out["RelationshipKind"] = {
        "description": (
            "Discriminator for the variant of a ``relationship-type``: exactly one of "
            "the following keys is set on a relationship's ``relationship-type``."
        ),
        "permissible_values": {
            "interacts": {"description": "Actor-to-nodes interaction."},
            "connects": {"description": "Interface-to-interface connection."},
            "deployed_in": {"description": "Containment: nodes deployed in a container."},
            "composed_of": {"description": "Composition: nodes composed by a container."},
            "options": {"description": "A set of alternative decisions."},
        },
    }
    return out


# ---------------------------------------------------------------------------
# Slots
# ---------------------------------------------------------------------------


def _collect_object_defs(
    schemas: "OrderedDict[str, dict]",
) -> list[tuple[str, str | None, dict]]:
    """Yield ``(filename, def_name | None, body)`` for every object def.

    The root of each schema file is yielded with ``def_name = None`` when it
    is itself a typed object (i.e. has ``properties``).
    """
    out: list[tuple[str, str | None, dict]] = []
    for fname, schema in schemas.items():
        if schema.get("type") == "object" and schema.get("properties"):
            out.append((fname, None, schema))
        for def_name, body in (schema.get("defs") or {}).items():
            if isinstance(body, dict) and (
                body.get("type") == "object" or body.get("properties")
            ):
                out.append((fname, def_name, body))
    return out


def slots_block(schemas: "OrderedDict[str, dict]") -> "OrderedDict[str, dict]":
    """Build the consolidated slot dict from every object's properties."""
    slots: "OrderedDict[str, dict]" = OrderedDict()
    seen: set[str] = set()
    for fname, def_name, body in _collect_object_defs(schemas):
        if (fname, def_name) not in DEFINITION_CLASSES:
            # Unmapped def — surface as a class via auto-derived name later;
            # skip slot collection for now (its properties are still walked).
            pass
        required_set = set(body.get("required") or [])
        for prop_name, prop in (body.get("properties") or {}).items():
            if prop_name == "additionalProperties":
                continue
            sname = slot_name_for(prop_name)
            if sname in seen:
                continue
            seen.add(sname)
            slots[sname] = convert_property(
                prop_name, prop, required=prop_name in required_set
            )

    # Always include identity / common slots even if no enrichment listed them.
    slots.setdefault(
        "unique_id",
        {"range": "string", "description": "Stable opaque identifier."},
    )

    # Apply enrichments (overlay on top of derived bodies).
    for sname, overlay in SLOT_ENRICHMENTS.items():
        body = slots.setdefault(sname, {"range": "string"})
        for k, v in overlay.items():
            if v is None:
                body.pop(k, None)  # None sentinel ->  delete the key
            else:
                body[k] = v

    return slots


# ---------------------------------------------------------------------------
# Classes
# ---------------------------------------------------------------------------


def _class_slots_for(body: dict) -> list[str]:
    """Return the list of LinkML slot names for an object body."""
    return [
        slot_name_for(p)
        for p in (body.get("properties") or {})
        if p != "additionalProperties"
    ]


def classes_block(schemas: "OrderedDict[str, dict]") -> "OrderedDict[str, dict]":
    """Build LinkML class dict from every mapped object def."""
    classes: "OrderedDict[str, dict]" = OrderedDict()

    for fname, def_name, body in _collect_object_defs(schemas):
        cname = DEFINITION_CLASSES.get((fname, def_name))
        if cname is None:
            continue
        slot_names = _class_slots_for(body)
        cls_body: dict[str, Any] = {}
        title = body.get("title")
        if title:
            cls_body["title"] = title
        desc = body.get("description")
        if desc:
            cls_body["description"] = desc
        if slot_names:
            cls_body["slots"] = slot_names
        classes[cname] = cls_body

    # Synthesise classes that aren't directly defs but are referenced.
    classes.setdefault(
        "OptionList",
        {
            "description": "Wrapper around the list of ``Decision`` alternatives in an options relationship.",
            "slots": ["decisions"],
        },
    )
    classes.setdefault(
        "RelationshipType",
        {
            "description": (
                "Tagged-union container for the variant body of a relationship. "
                "Exactly one of ``interacts``, ``connects``, ``deployed_in``, "
                "``composed_of``, ``options`` is populated; see "
                "``RelationshipKind`` for the discriminator values."
            ),
            "slots": [
                "interacts",
                "connects",
                "deployed_in",
                "composed_of",
                "options",
            ],
            "class_uri": "calm:RelationshipType",
            "in_subset": ["core"],
        },
    )

    # Apply enrichments
    for cname, overlay in CLASS_ENRICHMENTS.items():
        body = classes.setdefault(cname, {})
        for k, v in overlay.items():
            body[k] = v

    return classes


# Slots that the synthetic ``OptionList`` and ``RelationshipType`` classes need
# but the JSON Schema does not surface as top-level properties.
SYNTHETIC_SLOTS: dict[str, dict[str, Any]] = {
    "decisions": {
        "range": "Decision",
        "multivalued": True,
        "inlined": True,
        "inlined_as_list": True,
        "description": "Alternative decisions under an ``options`` relationship.",
    },
    "interacts": {"range": "InteractsRelationship", "inlined": True},
    "connects": {"range": "ConnectsRelationship", "inlined": True},
    "deployed_in": {
        "aliases": ["deployed-in"],
        "range": "DeployedInRelationship",
        "inlined": True,
    },
    "composed_of": {
        "aliases": ["composed-of"],
        "range": "ComposedOfRelationship",
        "inlined": True,
    },
    "options": {"range": "Decision", "multivalued": True, "inlined": True, "inlined_as_list": True},
}


# ---------------------------------------------------------------------------
# Assembly
# ---------------------------------------------------------------------------


def build_schema_text(
    schemas: "OrderedDict[str, dict] | None" = None,
) -> str:
    """Render the complete LinkML schema YAML text."""
    if schemas is None:
        schemas = load_all_schemas()

    slots = slots_block(schemas)
    # Inject synthetic slots not derived from JSON-Schema.
    for sname, sbody in SYNTHETIC_SLOTS.items():
        slots.setdefault(sname, sbody)

    classes = classes_block(schemas)
    enums = enums_block(schemas)

    blocks: list[list[str]] = [
        [GENERATED_HEADER, header_block()],
        [
            _emit_section("prefixes", prefixes_block()),
            _emit_scalar("default_prefix", DEFAULT_PREFIX),
            _emit_scalar("default_range", "string"),
        ],
        [_emit_section("imports", imports_block())],
        [_emit_section("subsets", subsets_block(), blank_between_entries=True)],
        [_emit_section("types", types_block(), blank_between_entries=True)],
        [_emit_section("enums", enums, blank_between_entries=True)],
        [_emit_section("slots", slots, blank_between_entries=True)],
        [_emit_section("classes", classes, blank_between_entries=True)],
    ]

    rendered: list[str] = []
    for sections in blocks:
        joined = "\n".join(s.rstrip() for s in sections if s.strip())
        if joined:  # pragma: no branch -- defensive; every block is populated
            rendered.append(joined)
    return "\n\n\n".join(rendered) + "\n"


def write_schema(target: Path | None = None) -> Path:
    target = target or SCHEMA_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(build_schema_text(), encoding="utf-8")
    return target


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(__doc__ or "").splitlines()[0] if __doc__ else ""
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; exit non-zero if the on-disk schema differs.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=SCHEMA_PATH,
        help=f"Output path (default: {SCHEMA_PATH})",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Write the schema to stdout instead of a file.",
    )
    args = parser.parse_args(argv)

    text = build_schema_text()

    if args.stdout:
        sys.stdout.write(text)
        return 0

    if args.check:
        if not args.out.exists():
            print(
                f"FAIL: {args.out} does not exist; run without --check to create it.",
                file=sys.stderr,
            )
            return 1
        if args.out.read_text(encoding="utf-8") != text:
            print(
                f"FAIL: {args.out} is out of date; rerun "
                f"``python {Path(__file__).name}``.",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {args.out} matches the generator output.")
        return 0

    written = write_schema(args.out)
    print(f"Wrote {written} ({len(text):,} bytes)")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
