// Code generated by linkml gen-cpp-header. DO NOT EDIT.
#pragma once

#include <cstdint>
#include <cstring>
#include <optional>
#include <string>
#include <vector>


namespace calm {

/// Wire-level protocol used by a relationship.
enum class Protocol {
    /// The HTTP protocol.
    HTTP,
    /// The HTTPS protocol.
    HTTPS,
    /// The FTP protocol.
    FTP,
    /// The SFTP protocol.
    SFTP,
    /// The JDBC protocol.
    JDBC,
    /// The WebSocket protocol.
    WEB_SOCKET,
    /// The SocketIO protocol.
    SOCKET_IO,
    /// The LDAP protocol.
    LDAP,
    /// The AMQP protocol.
    AMQP,
    /// The TLS protocol.
    TLS,
    /// The mTLS protocol.
    M_TLS,
    /// The TCP protocol.
    TCP
};

/// Convert Protocol to its string representation.
inline const char* to_string(Protocol value) {
    switch (value) {
        case Protocol::HTTP: return "HTTP";
        case Protocol::HTTPS: return "HTTPS";
        case Protocol::FTP: return "FTP";
        case Protocol::SFTP: return "SFTP";
        case Protocol::JDBC: return "JDBC";
        case Protocol::WEB_SOCKET: return "WebSocket";
        case Protocol::SOCKET_IO: return "SocketIO";
        case Protocol::LDAP: return "LDAP";
        case Protocol::AMQP: return "AMQP";
        case Protocol::TLS: return "TLS";
        case Protocol::M_TLS: return "mTLS";
        case Protocol::TCP: return "TCP";
    }
    return "unknown";
}

/// Parse a string into Protocol. Returns false if the string is not a valid value.
inline bool from_string(const char* str, Protocol& out) {
    if (std::strcmp(str, "HTTP") == 0) { out = Protocol::HTTP; return true; }
    if (std::strcmp(str, "HTTPS") == 0) { out = Protocol::HTTPS; return true; }
    if (std::strcmp(str, "FTP") == 0) { out = Protocol::FTP; return true; }
    if (std::strcmp(str, "SFTP") == 0) { out = Protocol::SFTP; return true; }
    if (std::strcmp(str, "JDBC") == 0) { out = Protocol::JDBC; return true; }
    if (std::strcmp(str, "WebSocket") == 0) { out = Protocol::WEB_SOCKET; return true; }
    if (std::strcmp(str, "SocketIO") == 0) { out = Protocol::SOCKET_IO; return true; }
    if (std::strcmp(str, "LDAP") == 0) { out = Protocol::LDAP; return true; }
    if (std::strcmp(str, "AMQP") == 0) { out = Protocol::AMQP; return true; }
    if (std::strcmp(str, "TLS") == 0) { out = Protocol::TLS; return true; }
    if (std::strcmp(str, "mTLS") == 0) { out = Protocol::M_TLS; return true; }
    if (std::strcmp(str, "TCP") == 0) { out = Protocol::TCP; return true; }
    return false;
}

/// Category of architecture node. The CALM JSON-Schema allows arbitrary strings; this enum lists the canonical values plus an escape hatch via ``any_of`` on the slot.
enum class NodeType {
    /// A actor node.
    ACTOR,
    /// A ecosystem node.
    ECOSYSTEM,
    /// A system node.
    SYSTEM,
    /// A service node.
    SERVICE,
    /// A database node.
    DATABASE,
    /// A network node.
    NETWORK,
    /// A ldap node.
    LDAP,
    /// A webclient node.
    WEBCLIENT,
    /// A data-asset node.
    DATA_ASSET
};

/// Convert NodeType to its string representation.
inline const char* to_string(NodeType value) {
    switch (value) {
        case NodeType::ACTOR: return "actor";
        case NodeType::ECOSYSTEM: return "ecosystem";
        case NodeType::SYSTEM: return "system";
        case NodeType::SERVICE: return "service";
        case NodeType::DATABASE: return "database";
        case NodeType::NETWORK: return "network";
        case NodeType::LDAP: return "ldap";
        case NodeType::WEBCLIENT: return "webclient";
        case NodeType::DATA_ASSET: return "data_asset";
    }
    return "unknown";
}

/// Parse a string into NodeType. Returns false if the string is not a valid value.
inline bool from_string(const char* str, NodeType& out) {
    if (std::strcmp(str, "actor") == 0) { out = NodeType::ACTOR; return true; }
    if (std::strcmp(str, "ecosystem") == 0) { out = NodeType::ECOSYSTEM; return true; }
    if (std::strcmp(str, "system") == 0) { out = NodeType::SYSTEM; return true; }
    if (std::strcmp(str, "service") == 0) { out = NodeType::SERVICE; return true; }
    if (std::strcmp(str, "database") == 0) { out = NodeType::DATABASE; return true; }
    if (std::strcmp(str, "network") == 0) { out = NodeType::NETWORK; return true; }
    if (std::strcmp(str, "ldap") == 0) { out = NodeType::LDAP; return true; }
    if (std::strcmp(str, "webclient") == 0) { out = NodeType::WEBCLIENT; return true; }
    if (std::strcmp(str, "data_asset") == 0) { out = NodeType::DATA_ASSET; return true; }
    return false;
}

/// Named unit of time used by ``TimeUnit``.
enum class TimeUnitName {
    /// Time unit: nanoseconds.
    NANOSECONDS,
    /// Time unit: microseconds.
    MICROSECONDS,
    /// Time unit: milliseconds.
    MILLISECONDS,
    /// Time unit: seconds.
    SECONDS,
    /// Time unit: minutes.
    MINUTES,
    /// Time unit: hours.
    HOURS,
    /// Time unit: days.
    DAYS,
    /// Time unit: weeks.
    WEEKS,
    /// Time unit: months.
    MONTHS,
    /// Time unit: quarters.
    QUARTERS,
    /// Time unit: years.
    YEARS
};

/// Convert TimeUnitName to its string representation.
inline const char* to_string(TimeUnitName value) {
    switch (value) {
        case TimeUnitName::NANOSECONDS: return "nanoseconds";
        case TimeUnitName::MICROSECONDS: return "microseconds";
        case TimeUnitName::MILLISECONDS: return "milliseconds";
        case TimeUnitName::SECONDS: return "seconds";
        case TimeUnitName::MINUTES: return "minutes";
        case TimeUnitName::HOURS: return "hours";
        case TimeUnitName::DAYS: return "days";
        case TimeUnitName::WEEKS: return "weeks";
        case TimeUnitName::MONTHS: return "months";
        case TimeUnitName::QUARTERS: return "quarters";
        case TimeUnitName::YEARS: return "years";
    }
    return "unknown";
}

/// Parse a string into TimeUnitName. Returns false if the string is not a valid value.
inline bool from_string(const char* str, TimeUnitName& out) {
    if (std::strcmp(str, "nanoseconds") == 0) { out = TimeUnitName::NANOSECONDS; return true; }
    if (std::strcmp(str, "microseconds") == 0) { out = TimeUnitName::MICROSECONDS; return true; }
    if (std::strcmp(str, "milliseconds") == 0) { out = TimeUnitName::MILLISECONDS; return true; }
    if (std::strcmp(str, "seconds") == 0) { out = TimeUnitName::SECONDS; return true; }
    if (std::strcmp(str, "minutes") == 0) { out = TimeUnitName::MINUTES; return true; }
    if (std::strcmp(str, "hours") == 0) { out = TimeUnitName::HOURS; return true; }
    if (std::strcmp(str, "days") == 0) { out = TimeUnitName::DAYS; return true; }
    if (std::strcmp(str, "weeks") == 0) { out = TimeUnitName::WEEKS; return true; }
    if (std::strcmp(str, "months") == 0) { out = TimeUnitName::MONTHS; return true; }
    if (std::strcmp(str, "quarters") == 0) { out = TimeUnitName::QUARTERS; return true; }
    if (std::strcmp(str, "years") == 0) { out = TimeUnitName::YEARS; return true; }
    return false;
}

/// Time interval denominator used by ``RateUnit``.
enum class RatePerUnit {
    /// Rate denominator: per nanosecond.
    NANOSECOND,
    /// Rate denominator: per microsecond.
    MICROSECOND,
    /// Rate denominator: per millisecond.
    MILLISECOND,
    /// Rate denominator: per second.
    SECOND,
    /// Rate denominator: per minute.
    MINUTE,
    /// Rate denominator: per hour.
    HOUR,
    /// Rate denominator: per day.
    DAY,
    /// Rate denominator: per week.
    WEEK,
    /// Rate denominator: per month.
    MONTH,
    /// Rate denominator: per quarter.
    QUARTER,
    /// Rate denominator: per year.
    YEAR
};

/// Convert RatePerUnit to its string representation.
inline const char* to_string(RatePerUnit value) {
    switch (value) {
        case RatePerUnit::NANOSECOND: return "nanosecond";
        case RatePerUnit::MICROSECOND: return "microsecond";
        case RatePerUnit::MILLISECOND: return "millisecond";
        case RatePerUnit::SECOND: return "second";
        case RatePerUnit::MINUTE: return "minute";
        case RatePerUnit::HOUR: return "hour";
        case RatePerUnit::DAY: return "day";
        case RatePerUnit::WEEK: return "week";
        case RatePerUnit::MONTH: return "month";
        case RatePerUnit::QUARTER: return "quarter";
        case RatePerUnit::YEAR: return "year";
    }
    return "unknown";
}

/// Parse a string into RatePerUnit. Returns false if the string is not a valid value.
inline bool from_string(const char* str, RatePerUnit& out) {
    if (std::strcmp(str, "nanosecond") == 0) { out = RatePerUnit::NANOSECOND; return true; }
    if (std::strcmp(str, "microsecond") == 0) { out = RatePerUnit::MICROSECOND; return true; }
    if (std::strcmp(str, "millisecond") == 0) { out = RatePerUnit::MILLISECOND; return true; }
    if (std::strcmp(str, "second") == 0) { out = RatePerUnit::SECOND; return true; }
    if (std::strcmp(str, "minute") == 0) { out = RatePerUnit::MINUTE; return true; }
    if (std::strcmp(str, "hour") == 0) { out = RatePerUnit::HOUR; return true; }
    if (std::strcmp(str, "day") == 0) { out = RatePerUnit::DAY; return true; }
    if (std::strcmp(str, "week") == 0) { out = RatePerUnit::WEEK; return true; }
    if (std::strcmp(str, "month") == 0) { out = RatePerUnit::MONTH; return true; }
    if (std::strcmp(str, "quarter") == 0) { out = RatePerUnit::QUARTER; return true; }
    if (std::strcmp(str, "year") == 0) { out = RatePerUnit::YEAR; return true; }
    return false;
}

/// Direction of flow on a transition.
enum class TransitionDirection {
    /// Flow direction: source-to-destination.
    SOURCE_TO_DESTINATION,
    /// Flow direction: destination-to-source.
    DESTINATION_TO_SOURCE
};

/// Convert TransitionDirection to its string representation.
inline const char* to_string(TransitionDirection value) {
    switch (value) {
        case TransitionDirection::SOURCE_TO_DESTINATION: return "source_to_destination";
        case TransitionDirection::DESTINATION_TO_SOURCE: return "destination_to_source";
    }
    return "unknown";
}

/// Parse a string into TransitionDirection. Returns false if the string is not a valid value.
inline bool from_string(const char* str, TransitionDirection& out) {
    if (std::strcmp(str, "source_to_destination") == 0) { out = TransitionDirection::SOURCE_TO_DESTINATION; return true; }
    if (std::strcmp(str, "destination_to_source") == 0) { out = TransitionDirection::DESTINATION_TO_SOURCE; return true; }
    return false;
}

/// Discriminator for the variant of a ``relationship-type``: exactly one of the following keys is set on a relationship's ``relationship-type``.
enum class RelationshipKind {
    /// Actor-to-nodes interaction.
    INTERACTS,
    /// Interface-to-interface connection.
    CONNECTS,
    /// Containment: nodes deployed in a container.
    DEPLOYED_IN,
    /// Composition: nodes composed by a container.
    COMPOSED_OF,
    /// A set of alternative decisions.
    OPTIONS
};

/// Convert RelationshipKind to its string representation.
inline const char* to_string(RelationshipKind value) {
    switch (value) {
        case RelationshipKind::INTERACTS: return "interacts";
        case RelationshipKind::CONNECTS: return "connects";
        case RelationshipKind::DEPLOYED_IN: return "deployed_in";
        case RelationshipKind::COMPOSED_OF: return "composed_of";
        case RelationshipKind::OPTIONS: return "options";
    }
    return "unknown";
}

/// Parse a string into RelationshipKind. Returns false if the string is not a valid value.
inline bool from_string(const char* str, RelationshipKind& out) {
    if (std::strcmp(str, "interacts") == 0) { out = RelationshipKind::INTERACTS; return true; }
    if (std::strcmp(str, "connects") == 0) { out = RelationshipKind::CONNECTS; return true; }
    if (std::strcmp(str, "deployed_in") == 0) { out = RelationshipKind::DEPLOYED_IN; return true; }
    if (std::strcmp(str, "composed_of") == 0) { out = RelationshipKind::COMPOSED_OF; return true; }
    if (std::strcmp(str, "options") == 0) { out = RelationshipKind::OPTIONS; return true; }
    return false;
}

/// Top-level CALM architecture document.
struct Architecture {
    std::vector<Node> nodes = {};
    std::vector<Relationship> relationships = {};
    std::optional<std::string> metadata = std::nullopt;
    std::optional<Control> controls = std::nullopt;
    std::vector<Flow> flows = {};
    /// External links to ADRs (Architecture Decision Records) or similar documents that provide context or decisions related to the architecture. These can be URLs or references to internal documentation.
    std::vector<std::string> adrs = {};
};


/// A logical or physical element of an architecture (system, service, actor, ...).
struct Node {
    /// Stable opaque identifier used to cross-link CALM elements.
    std::string unique_id;
    /// Category of the node (system, service, actor, etc.).
    NodeType node_type;
    /// Short human-readable name.
    std::string name;
    /// Free-form description of the element.
    std::string description;
    std::optional<std::string> details = std::nullopt;
    /// Interface definitions exposed by nodes.
    std::vector<InterfaceDefinition> interfaces = {};
    std::optional<Control> controls = std::nullopt;
    std::optional<std::string> metadata = std::nullopt;
};


/// A typed link between architecture elements.
struct Relationship {
    /// Stable opaque identifier used to cross-link CALM elements.
    std::string unique_id;
    /// Free-form description of the element.
    std::optional<std::string> description = std::nullopt;
    RelationshipType relationship_type;
    std::optional<Protocol> protocol = std::nullopt;
    std::optional<std::string> metadata = std::nullopt;
    std::optional<Control> controls = std::nullopt;
};


/// An ``interacts`` relationship between an actor and one or more nodes.
struct InteractsRelationship {
    std::string actor;
    std::vector<Node> nodes = {};
};


/// A ``connects`` relationship between two node interfaces.
struct ConnectsRelationship {
    NodeInterface source;
    NodeInterface destination;
};


/// A ``deployed-in`` containment relationship.
struct DeployedInRelationship {
    std::string container;
    std::vector<Node> nodes = {};
};


/// A ``composed-of`` containment relationship.
struct ComposedOfRelationship {
    std::string container;
    std::vector<Node> nodes = {};
};


/// A candidate decision within an ``options`` relationship.
struct Decision {
    /// Free-form description of the element.
    std::string description;
    std::vector<Node> nodes = {};
    std::vector<Relationship> relationships = {};
    std::optional<Control> controls = std::nullopt;
};


/// A single control requirement and its inline / referenced configuration.
struct ControlDetail {
    /// The requirement schema that specifies how a control should be defined
    std::string requirement_url;
    /// The configuration of how the control requirement schema is met
    std::optional<std::string> config_url = std::nullopt;
    /// Inline configuration of how the control requirement schema is met
    std::optional<std::string> config = std::nullopt;
};


/// A named control attached to an architecture element.
struct Control {
};


/// Domain-defined control requirement that controls can reference.
struct ControlRequirement {
    /// The unique identifier of this control, which has the potential to be used for linking evidence
    std::string control_id;
    /// Short human-readable name.
    std::string name;
    /// Free-form description of the element.
    std::string description;
};


/// Cross-cutting annotation attached to nodes, relationships, or flows.
struct Decorator {
    /// Stable opaque identifier used to cross-link CALM elements.
    std::string unique_id;
    /// Type of decorator - a free-form string identifying the decorator category
    std::string type;
    /// Array of file paths or URLs referencing the CALM documents (patterns, architectures, or controls) this decorator targets
    std::vector<std::string> target = {};
    /// Array of unique-ids referencing nodes, relationships, flows, or other architecture elements
    std::vector<std::string> applies_to = {};
    /// Free-form JSON object containing the decorator's data
    std::string data;
};


/// Top-level CALM evidence document linking control configurations to evidence artefacts.
struct EvidenceDocument {
    std::string evidence;
};


/// A single step in a flow, anchored on a relationship.
struct Transition {
    /// Unique identifier for the relationship in the architecture
    std::string relationship_unique_id;
    /// Indicates the sequence of the relationship in the flow
    int32_t sequence_number;
    /// Free-form description of the element.
    std::string description;
    /// Direction of flow on the transition.
    std::optional<TransitionDirection> direction = std::nullopt;
};


/// Business flow mapped onto architecture relationships.
struct Flow {
    /// Stable opaque identifier used to cross-link CALM elements.
    std::string unique_id;
    /// Short human-readable name.
    std::string name;
    /// Free-form description of the element.
    std::string description;
    /// The requirement schema that specifies how a control should be defined
    std::optional<std::string> requirement_url = std::nullopt;
    std::vector<Transition> transitions = {};
    std::optional<Control> controls = std::nullopt;
    std::optional<std::string> metadata = std::nullopt;
};


/// Modular interface definition referencing an external schema.
struct InterfaceDefinition {
    /// Stable opaque identifier used to cross-link CALM elements.
    std::string unique_id;
    /// URI of the external schema this interface configuration conforms to
    std::string definition_url;
    /// Inline configuration of how the control requirement schema is met
    std::string config;
};


/// Inline (free-form) interface definition keyed by unique-id.
struct InterfaceType {
    /// Stable opaque identifier used to cross-link CALM elements.
    std::string unique_id;
};


/// Reference to one or more interfaces exposed by a node.
struct NodeInterface {
    std::string node;
    /// Interface definitions exposed by nodes.
    std::vector<InterfaceDefinition> interfaces = {};
};


/// CALM timeline document capturing architecture moments over time.
struct Timeline {
    /// The unique-id of the current architecture moment within the timeline.
    std::optional<std::string> current_moment = std::nullopt;
    /// A list of significant architecture states or points in time, each represented as a 'moment'.
    std::vector<std::string> moments = {};
    std::optional<std::string> metadata = std::nullopt;
};


/// An architecture moment - a point-in-time snapshot of the architecture.
struct NodeMoment : public Node {
    /// Stable opaque identifier used to cross-link CALM elements.
    std::string unique_id;
    /// Short human-readable name.
    std::string name;
    /// Free-form description of the element.
    std::string description;
    std::optional<Control> controls = std::nullopt;
    std::optional<std::string> metadata = std::nullopt;
    /// Category of the node (system, service, actor, etc.).
    NodeType node_type;
    /// The date when this architecture moment came into effect.
    std::optional<std::string> valid_from = std::nullopt;
    /// External links to ADRs (Architecture Decision Records) or similar documents that provide context or decisions related to the architecture. These can be URLs or references to internal documentation.
    std::vector<std::string> adrs = {};
    /// Interface definitions exposed by nodes.
    std::vector<InterfaceDefinition> interfaces = {};
    std::string details;
};


/// A quantity of time expressed as a numeric value and a unit.
struct TimeUnit {
    /// The unit of time (e.g., seconds, minutes, hours).
    TimeUnitName unit;
    /// The numeric value representing the amount of time.
    float value;
};


/// A rate (count per time unit), e.g. operations per second.
struct RateUnit {
    /// The numeric value representing the rate.
    float rate;
    /// The time unit defining the rate interval.
    RatePerUnit per;
};


/// Wrapper around the list of ``Decision`` alternatives in an options relationship.
struct OptionList {
    /// Alternative decisions under an ``options`` relationship.
    std::vector<Decision> decisions = {};
};


/// Tagged-union container for the variant body of a relationship. Exactly one of ``interacts``, ``connects``, ``deployed_in``, ``composed_of``, ``options`` is populated; see ``RelationshipKind`` for the discriminator values.
struct RelationshipType {
    std::optional<InteractsRelationship> interacts = std::nullopt;
    std::optional<ConnectsRelationship> connects = std::nullopt;
    std::optional<DeployedInRelationship> deployed_in = std::nullopt;
    std::optional<ComposedOfRelationship> composed_of = std::nullopt;
    std::vector<Decision> options = {};
};


} // namespace calm
