// Code generated by linkml-golanggen. DO NOT EDIT.
package calm

import (
	"time"
)
// Wire-level protocol used by a relationship.
type Protocol string

const (
	// The HTTP protocol.
	ProtocolHTTP Protocol = "HTTP"
	// The HTTPS protocol.
	ProtocolHTTPS Protocol = "HTTPS"
	// The FTP protocol.
	ProtocolFTP Protocol = "FTP"
	// The SFTP protocol.
	ProtocolSFTP Protocol = "SFTP"
	// The JDBC protocol.
	ProtocolJDBC Protocol = "JDBC"
	// The WebSocket protocol.
	ProtocolWebSocket Protocol = "WebSocket"
	// The SocketIO protocol.
	ProtocolSocketIO Protocol = "SocketIO"
	// The LDAP protocol.
	ProtocolLDAP Protocol = "LDAP"
	// The AMQP protocol.
	ProtocolAMQP Protocol = "AMQP"
	// The TLS protocol.
	ProtocolTLS Protocol = "TLS"
	// The mTLS protocol.
	ProtocolMTLS Protocol = "mTLS"
	// The TCP protocol.
	ProtocolTCP Protocol = "TCP"
)
// Category of architecture node. The CALM JSON-Schema allows arbitrary strings; this enum lists the canonical values plus an escape hatch via ``any_of`` on the slot.
type NodeType string

const (
	// A actor node.
	NodeTypeActor NodeType = "actor"
	// A ecosystem node.
	NodeTypeEcosystem NodeType = "ecosystem"
	// A system node.
	NodeTypeSystem NodeType = "system"
	// A service node.
	NodeTypeService NodeType = "service"
	// A database node.
	NodeTypeDatabase NodeType = "database"
	// A network node.
	NodeTypeNetwork NodeType = "network"
	// A ldap node.
	NodeTypeLdap NodeType = "ldap"
	// A webclient node.
	NodeTypeWebclient NodeType = "webclient"
	// A data-asset node.
	NodeTypeDataAsset NodeType = "data_asset"
)
// Named unit of time used by ``TimeUnit``.
type TimeUnitName string

const (
	// Time unit: nanoseconds.
	TimeUnitNameNanoseconds TimeUnitName = "nanoseconds"
	// Time unit: microseconds.
	TimeUnitNameMicroseconds TimeUnitName = "microseconds"
	// Time unit: milliseconds.
	TimeUnitNameMilliseconds TimeUnitName = "milliseconds"
	// Time unit: seconds.
	TimeUnitNameSeconds TimeUnitName = "seconds"
	// Time unit: minutes.
	TimeUnitNameMinutes TimeUnitName = "minutes"
	// Time unit: hours.
	TimeUnitNameHours TimeUnitName = "hours"
	// Time unit: days.
	TimeUnitNameDays TimeUnitName = "days"
	// Time unit: weeks.
	TimeUnitNameWeeks TimeUnitName = "weeks"
	// Time unit: months.
	TimeUnitNameMonths TimeUnitName = "months"
	// Time unit: quarters.
	TimeUnitNameQuarters TimeUnitName = "quarters"
	// Time unit: years.
	TimeUnitNameYears TimeUnitName = "years"
)
// Time interval denominator used by ``RateUnit``.
type RatePerUnit string

const (
	// Rate denominator: per nanosecond.
	RatePerUnitNanosecond RatePerUnit = "nanosecond"
	// Rate denominator: per microsecond.
	RatePerUnitMicrosecond RatePerUnit = "microsecond"
	// Rate denominator: per millisecond.
	RatePerUnitMillisecond RatePerUnit = "millisecond"
	// Rate denominator: per second.
	RatePerUnitSecond RatePerUnit = "second"
	// Rate denominator: per minute.
	RatePerUnitMinute RatePerUnit = "minute"
	// Rate denominator: per hour.
	RatePerUnitHour RatePerUnit = "hour"
	// Rate denominator: per day.
	RatePerUnitDay RatePerUnit = "day"
	// Rate denominator: per week.
	RatePerUnitWeek RatePerUnit = "week"
	// Rate denominator: per month.
	RatePerUnitMonth RatePerUnit = "month"
	// Rate denominator: per quarter.
	RatePerUnitQuarter RatePerUnit = "quarter"
	// Rate denominator: per year.
	RatePerUnitYear RatePerUnit = "year"
)
// Direction of flow on a transition.
type TransitionDirection string

const (
	// Flow direction: source-to-destination.
	TransitionDirectionSourceToDestination TransitionDirection = "source_to_destination"
	// Flow direction: destination-to-source.
	TransitionDirectionDestinationToSource TransitionDirection = "destination_to_source"
)
// Discriminator for the variant of a ``relationship-type``: exactly one of the following keys is set on a relationship's ``relationship-type``.
type RelationshipKind string

const (
	// Actor-to-nodes interaction.
	RelationshipKindInteracts RelationshipKind = "interacts"
	// Interface-to-interface connection.
	RelationshipKindConnects RelationshipKind = "connects"
	// Containment: nodes deployed in a container.
	RelationshipKindDeployedIn RelationshipKind = "deployed_in"
	// Composition: nodes composed by a container.
	RelationshipKindComposedOf RelationshipKind = "composed_of"
	// A set of alternative decisions.
	RelationshipKindOptions RelationshipKind = "options"
)
// Top-level CALM architecture document.
type Architecture struct {
	Nodes []Node `json:"nodes,omitempty"`
	Relationships []Relationship `json:"relationships,omitempty"`
	Metadata *string `json:"metadata,omitempty"`
	Controls *Control `json:"controls,omitempty"`
	Flows []Flow `json:"flows,omitempty"`
	// External links to ADRs (Architecture Decision Records) or similar documents that provide context or decisions related to the architecture. These can be URLs or references to internal documentation.
	Adrs []string `json:"adrs,omitempty"`
}

// A logical or physical element of an architecture (system, service, actor, ...).
type Node struct {
	// Stable opaque identifier used to cross-link CALM elements.
	UniqueId string `json:"unique_id"`
	// Category of the node (system, service, actor, etc.).
	NodeType NodeType `json:"node_type"`
	// Short human-readable name.
	Name string `json:"name"`
	// Free-form description of the element.
	Description string `json:"description"`
	Details *string `json:"details,omitempty"`
	// Interface definitions exposed by nodes.
	Interfaces []InterfaceDefinition `json:"interfaces,omitempty"`
	Controls *Control `json:"controls,omitempty"`
	Metadata *string `json:"metadata,omitempty"`
}

// A typed link between architecture elements.
type Relationship struct {
	// Stable opaque identifier used to cross-link CALM elements.
	UniqueId string `json:"unique_id"`
	// Free-form description of the element.
	Description *string `json:"description,omitempty"`
	RelationshipType RelationshipType `json:"relationship_type"`
	Protocol Protocol `json:"protocol,omitempty"`
	Metadata *string `json:"metadata,omitempty"`
	Controls *Control `json:"controls,omitempty"`
}

// An ``interacts`` relationship between an actor and one or more nodes.
type InteractsRelationship struct {
	Actor string `json:"actor"`
	Nodes []NodeId `json:"nodes"`
}

// A ``connects`` relationship between two node interfaces.
type ConnectsRelationship struct {
	Source NodeInterface `json:"source"`
	Destination NodeInterface `json:"destination"`
}

// A ``deployed-in`` containment relationship.
type DeployedInRelationship struct {
	Container string `json:"container"`
	Nodes []NodeId `json:"nodes"`
}

// A ``composed-of`` containment relationship.
type ComposedOfRelationship struct {
	Container string `json:"container"`
	Nodes []NodeId `json:"nodes"`
}

// A candidate decision within an ``options`` relationship.
type Decision struct {
	// Free-form description of the element.
	Description string `json:"description"`
	Nodes []Node `json:"nodes"`
	Relationships []Relationship `json:"relationships"`
	Controls *Control `json:"controls,omitempty"`
}

// A single control requirement and its inline / referenced configuration.
type ControlDetail struct {
	// The requirement schema that specifies how a control should be defined
	RequirementUrl string `json:"requirement_url"`
	// The configuration of how the control requirement schema is met
	ConfigUrl *string `json:"config_url,omitempty"`
	// Inline configuration of how the control requirement schema is met
	Config *string `json:"config,omitempty"`
}

// A named control attached to an architecture element.
type Control struct {
}

// Domain-defined control requirement that controls can reference.
type ControlRequirement struct {
	// The unique identifier of this control, which has the potential to be used for linking evidence
	ControlId string `json:"control_id"`
	// Short human-readable name.
	Name string `json:"name"`
	// Free-form description of the element.
	Description string `json:"description"`
}

// Cross-cutting annotation attached to nodes, relationships, or flows.
type Decorator struct {
	// Stable opaque identifier used to cross-link CALM elements.
	UniqueId string `json:"unique_id"`
	// Type of decorator - a free-form string identifying the decorator category
	Type string `json:"type"`
	// Array of file paths or URLs referencing the CALM documents (patterns, architectures, or controls) this decorator targets
	Target []string `json:"target"`
	// Array of unique-ids referencing nodes, relationships, flows, or other architecture elements
	AppliesTo []string `json:"applies_to"`
	// Free-form JSON object containing the decorator's data
	Data string `json:"data"`
}

// Top-level CALM evidence document linking control configurations to evidence artefacts.
type EvidenceDocument struct {
	Evidence string `json:"evidence"`
}

// A single step in a flow, anchored on a relationship.
type Transition struct {
	// Unique identifier for the relationship in the architecture
	RelationshipUniqueId string `json:"relationship_unique_id"`
	// Indicates the sequence of the relationship in the flow
	SequenceNumber int `json:"sequence_number"`
	// Free-form description of the element.
	Description string `json:"description"`
	// Direction of flow on the transition.
	Direction TransitionDirection `json:"direction,omitempty"`
}

// Business flow mapped onto architecture relationships.
type Flow struct {
	// Stable opaque identifier used to cross-link CALM elements.
	UniqueId string `json:"unique_id"`
	// Short human-readable name.
	Name string `json:"name"`
	// Free-form description of the element.
	Description string `json:"description"`
	// The requirement schema that specifies how a control should be defined
	RequirementUrl *string `json:"requirement_url,omitempty"`
	Transitions []Transition `json:"transitions"`
	Controls *Control `json:"controls,omitempty"`
	Metadata *string `json:"metadata,omitempty"`
}

// Modular interface definition referencing an external schema.
type InterfaceDefinition struct {
	// Stable opaque identifier used to cross-link CALM elements.
	UniqueId string `json:"unique_id"`
	// URI of the external schema this interface configuration conforms to
	DefinitionUrl string `json:"definition_url"`
	// Inline configuration of how the control requirement schema is met
	Config string `json:"config"`
}

// Inline (free-form) interface definition keyed by unique-id.
type InterfaceType struct {
	// Stable opaque identifier used to cross-link CALM elements.
	UniqueId string `json:"unique_id"`
}

// Reference to one or more interfaces exposed by a node.
type NodeInterface struct {
	Node string `json:"node"`
	// Interface definitions exposed by nodes.
	Interfaces []InterfaceDefinition `json:"interfaces,omitempty"`
}

// CALM timeline document capturing architecture moments over time.
type Timeline struct {
	// The unique-id of the current architecture moment within the timeline.
	CurrentMoment *string `json:"current_moment,omitempty"`
	// A list of significant architecture states or points in time, each represented as a 'moment'.
	Moments []string `json:"moments"`
	Metadata *string `json:"metadata,omitempty"`
}

// An architecture moment - a point-in-time snapshot of the architecture.
type NodeMoment struct {
	// Embedded types for inheritance
	Node `json:",inline"`
	// Stable opaque identifier used to cross-link CALM elements.
	UniqueId string `json:"unique_id"`
	// Short human-readable name.
	Name string `json:"name"`
	// Free-form description of the element.
	Description string `json:"description"`
	Controls *Control `json:"controls,omitempty"`
	Metadata *string `json:"metadata,omitempty"`
	// Category of the node (system, service, actor, etc.).
	NodeType NodeType `json:"node_type"`
	// The date when this architecture moment came into effect.
	ValidFrom *time.Time `json:"valid_from,omitempty"`
	// External links to ADRs (Architecture Decision Records) or similar documents that provide context or decisions related to the architecture. These can be URLs or references to internal documentation.
	Adrs []string `json:"adrs,omitempty"`
	// Interface definitions exposed by nodes.
	Interfaces []InterfaceDefinition `json:"interfaces,omitempty"`
	Details string `json:"details"`
}

// A quantity of time expressed as a numeric value and a unit.
type TimeUnit struct {
	// The unit of time (e.g., seconds, minutes, hours).
	Unit TimeUnitName `json:"unit"`
	// The numeric value representing the amount of time.
	Value float64 `json:"value"`
}

// A rate (count per time unit), e.g. operations per second.
type RateUnit struct {
	// The numeric value representing the rate.
	Rate float64 `json:"rate"`
	// The time unit defining the rate interval.
	Per RatePerUnit `json:"per"`
}

// Wrapper around the list of ``Decision`` alternatives in an options relationship.
type OptionList struct {
	// Alternative decisions under an ``options`` relationship.
	Decisions []Decision `json:"decisions,omitempty"`
}

// Tagged-union container for the variant body of a relationship. Exactly one of ``interacts``, ``connects``, ``deployed_in``, ``composed_of``, ``options`` is populated; see ``RelationshipKind`` for the discriminator values.
type RelationshipType struct {
	Interacts *InteractsRelationship `json:"interacts,omitempty"`
	Connects *ConnectsRelationship `json:"connects,omitempty"`
	DeployedIn *DeployedInRelationship `json:"deployed_in,omitempty"`
	ComposedOf *ComposedOfRelationship `json:"composed_of,omitempty"`
	Options []Decision `json:"options,omitempty"`
}

type NodeId string


